# PowerShell installer generated by Blender Launcher
Write-Host "Starting build tools installer (attempting winget)..."
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
  Write-Host "winget not found on this system. Please install winget or follow the README in the build_tools folder."
} else {
  Write-Host "Installing cmake via winget (Kitware.CMake)"
  & winget install --id Kitware.CMake -e --accept-package-agreements --accept-source-agreements; if ($LASTEXITCODE -ne 0) { Write-Host "cmake install failed or already present (exit $LASTEXITCODE)" }
  Write-Host "Installer finished (some installs may require further configuration or reboot)."
}